remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: RELIEFLINK
description: Ứng dụng hỗ trợ cứu nạn khẩn cấp và quản lý nguồn lực
show_downloads: true
github:
  zip_url: https://github.com/olp-dtu-2024/DTU-GreenHope/zipball/main
  tar_url: https://github.com/olp-dtu-2024/DTU-GreenHope/tarball/main
  repository_url: https://github.com/olp-dtu-2024/DTU-GreenHope 